[build]
  command = "npm install && npm run build:client"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
